### ISSUE TITLE
New directory structure

### ISSUE THREAD

**Issue by TomasKulhanek** [vais-ral/CCPi-Regularisation-Toolkit#103]
I recommend to compact and simplify directory structure as follows:
- `build` directory for direct build, run and other scripts to compile, test and run
- `demos` for demos, move Python and Matlab demos here
- `recipe` for conda related recipe, configuration and scripts
- `src` for all sources in C/C++, Python and Matlab
  - `/src/Core` move current `/Core` dir, should be in src
  - `/src/Matlab` move from `/Wrappers/Matlab/src`
  - `/src/Python` move from `/Wrappers/Python/src`
- `test` for all unit tests or integration tests, note that `/recipe/run_tests.py` should contain only basic tests which are executed during build, but this `test` directory should contain all low level unit testing during development cycle as recommended by TDD.

**Comment by TomasKulhanek** [comment]
Any thoughs and feedback on this issue welcomed. I Also submitted PR with new directories, changes in cmake and build script to check whether it pass the build and test process - last dev build passed.

**Comment by TomasKulhanek** [comment]
So compared to dir structure at docs https://cil.readthedocs.io/en/latest/developer_guide.html#
I propose the following changes:
- `project_name/` - OK
  - `CMake/` - as this is cmake specific routines for building - I propose to have it directly in `build/`, probably there are few files so no need to have another special directory `build/CMake`, but just `build/`
  - `CMakeLists.txt` - OK
  - `License.txt` -OK
  - `Core/` - I propose to have it in `src/Core`
  - `recipes/` - rename to `recipe`, subdirs in it can contain some special recipes, content from `Wrappers/Python/conda-recipe`
  - `Wrappers/` - I propose to dismiss and all content separate to either `docs` which includes demos, `src` and `recipes`
    - `Python/` -  move to `src/Python` and `recipe/` and demos etc. to docs, e.g.`docs/demos`
    - `Avizo/` - move to `src/Avizo`
    -  `Paraview/` - move to `src/Paraview`
    -  `Tomviz/` - move to `src/Tomviz`

**Comment by dkazanc** [comment]
Thanks Tomas. I'm not sure about all demos being into docs? Personally I'd not be looking for demos in docs, could we create a specific directory `Demos` ? I guess it is better than keep them in `src` ?

**Comment by TomasKulhanek** [comment]
OK with `demos` in separate directory. 
In case of regularisation, I put into `docs` all demos, data, images and one txt file. Txt file I believe can be dismissed, so instead of `docs` a `demos` name is more sufficient. Docs are covered in README.md and in cil.readthedocs.org

- `demos`

**Comment by paskino** [comment]
> So compared to dir structure at docs https://cil.readthedocs.io/en/latest/developer_guide.html#
> I propose the following changes:
> 
> * `project_name/` - OK
>   
>   * `CMake/` - as this is cmake specific routines for building - I propose to have it directly in `build/`, probably there are few files so no need to have another special directory `build/CMake`, but just `build/`
>   * `CMakeLists.txt` - OK
>   * `License.txt` -OK
>   * `Core/` - I propose to have it in `src/Core`
>   * `recipes/` - rename to `recipe`, subdirs in it can contain some special recipes, content from `Wrappers/Python/conda-recipe`
>   * `Wrappers/` - I propose to dismiss and all content separate to either `docs` which includes demos, `src` and `recipes`
>     
>     * `Python/` -  move to `src/Python` and `recipe/` and demos etc. to docs, e.g.`docs/demos`
>     * `Avizo/` - move to `src/Avizo`
>     * `Paraview/` - move to `src/Paraview`
>     * `Tomviz/` - move to `src/Tomviz`

Shall we have a `test` directory with unit tests?

**Comment by TomasKulhanek** [comment]
| Shall we have a `test` directory with unit tests?
It's already there (see first comment).

**Comment by dkazanc** [comment]
unfortunately tests still fail on: 
`FileNotFoundError: [Errno 2] No such file or directory: 'lena_gray_512.tif'`
It's now in master.
