### ISSUE TITLE
current test phase depends on pillow

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-Regularisation-Toolkit#113]
Currently the python tests require pillow. Could we save the image also as `npy`, so that we won't need the additional requirement?

NumPy files are basically binary array saved to file with a descriptive header, for which I've even written a small C++ reader.  This means that we could write tests in C/C++ reading the `npy` file without problems.

**Comment by dkazanc** [comment]
Makes sense. Options:
1. Save image into a binary file and provide a reader for both Matlab and Python. 
2. Save into `npy` I use your header to read it from both  Matlab and Python? 

I'd guess 1 is the simplest?

**Comment by dkazanc** [comment]
sorted with #124
