### ISSUE TITLE
find_package openmp

### ISSUE THREAD

**Issue by rijobro** [vais-ral/CCPi-Regularisation-Toolkit#136]
The `find_package(OpenMP)` should have the `REQUIRED` flag. 

It should also be moved up one level, as it is currently placed in the `Core` folder, but is also required in the `Python` folder.

**Comment by dkazanc** [comment]
Thanks, it has been corrected in this PR #137 
It is OK @paskino ?

**Comment by dkazanc** [comment]
I added the requirement in [here](https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/pdtv/src/CMakeLists.txt). I, however left the requirement inside Core folder.

**Comment by paskino** [comment]
@dkazanc since you moved `find_package(OpendMP REQUIRED)` up one directory it is not necessary to call it also in `/src/Core`
