### ISSUE TITLE
Lipschitz constant in FGP_TV for 3D

### ISSUE THREAD

**Issue by epapoutsellis** [vais-ral/CCPi-Regularisation-Toolkit#149]
Hi @dkazanc 

Why `L = 26` [here](https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/master/src/Core/regularisers_CPU/FGP_TV_core.c#L241) for the 3D case? I think it should be `L=sqrt(12)`.

**Comment by dkazanc** [comment]
Hi, thanks this could be an error: 
is it also sqrt(12) for 2D case [here](https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/9074828d1e0876b41bdb40da8f622824e6614e94/src/Core/regularisers_CPU/FGP_TV_core.c#L192) ?

**Comment by epapoutsellis** [comment]
No, 2D case is np.sqrt(8). I think (haven't check for different bc, it should be true) it should be
sqrt( 2^2 + 2^2 + ... number of dimensions + 2^2)

**Comment by dkazanc** [comment]
I see, so 2D: multip = (1.0f/(sqrt(8.0)*lambda)) and for 3D: multip = (1.0f/(sqrt(12.0)*lambda))

**Comment by epapoutsellis** [comment]
Yes but without the square roots
