### ISSUE TITLE
skip cuda tests if cuda driver is not compatible with cuda runtime version

### ISSUE THREAD

**Issue by TomasKulhanek** [vais-ral/CCPi-Regularisation-Toolkit#79]
Skip GPU tests when "code: 35, reason: CUDA driver version is insufficient for CUDA runtime version".
Currently tests fails on

Executing transaction: ...working... done
Error: /home/jenkins/workspace/CILsingle/CCPi-Regularisation-Toolkit/Core/regularisers_GPU/Diffus_4thO_GPU_core.cu:234, code: 35, reason: CUDA driver version is insufficient for CUDA runtime version
Tests failed for ccpi-regulariser-0.10.2-np111py36_0.tar.bz2 - moving package to /home/jenkins/conda-bld/broken
WARNING:conda_build.build:Tests failed for ccpi-regulariser-0.10.2-np111py36_0.tar.bz2 - moving package to /home/jenkins/conda-bld/broken
TESTS FAILED: ccpi-regulariser-0.10.2-np111py36_0.tar.bz2
Build step 'Execute shell' marked build as failure

**Comment by dkazanc** [comment]
makes sense to skip the tests when the warning happens. I've got this yesterday actually after upgrading to CUDA 10 forgetting to upgrade the driver. 
I've got a different test FAIL: test_ROF_TV_CPU_vs_GPU  but I know the reason. Going to work in the dev_jenkins branch to fix it
