### ISSUE TITLE
webhook for jenkins

### ISSUE THREAD

**Issue by TomasKulhanek** [vais-ral/CCPi-Regularisation-Toolkit#85]
https://wiki.jenkins.io/display/JENKINS/Github+Plugin states 2 modes:

1) manual, you need to put URL int Settings->Webhook->Payload URL: https://anvil.softeng-support.ac.uk/jenkins/github-webhook/
Don't have permission to do that in github repo.

2) automatic, you need to enable in Jenkins Global Config the github repo.
Don't have permission in Jenkins to see such configuration.

**Comment by vais-ral** [comment]
I added the webhook on the repo triggered by push, PR, PR reviews, PR comments.

**Comment by TomasKulhanek** [comment]
seems to work now
