### ISSUE TITLE
Add binaries for Windows

### ISSUE THREAD

**Issue by dkazanc** [vais-ral/CCPi-Regularisation-Toolkit#89]
Looks like binaries are available for Linux only, would it be difficult to add Windows as well?

**Comment by paskino** [comment]
Currently there is no CI for windows. I can manually upload. Let's merge #111 first.

**Comment by dkazanc** [comment]
@paskino How difficult will be to add CS for Windows?

**Comment by paskino** [comment]
At the moment Jenkins can only build for Linux and OSX

**Comment by paskino** [comment]
Binaries for windows are manually created for the release version https://anaconda.org/ccpi/ccpi-regulariser
