### ISSUE TITLE
Windows10/python3.5 import PIL issue

### ISSUE THREAD

**Issue by dkazanc** [vais-ral/CCPi-Regularisation-Toolkit#90]
This happened 
```
  File "C:\Users\kjy41806\conda-bld\ccpi-regulariser_1548191960811\test_tmp\run_test.py", line 10, in <module>
    from PIL import Image
  File "C:\Users\kjy41806\conda-bld\ccpi-regulariser_1548191960811\_test_env\lib\site-packages\PIL\Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.
```
Which seems repeating this [ISSUE](https://stackoverflow.com/questions/43264773/pil-dll-load-failed-specified-procedure-could-not-be-found)

Looking for a workaround atm.

**Comment by dkazanc** [comment]
OK, so apparently `import Image` has changed in recent `pillow`. The problem is that I cannot force it to use the older version and it installs `pillow:  5.4.1` for tests.

**Comment by dkazanc** [comment]
@paskino is it possible to specify versions of installed packages for `_test_env`? cheers

**Comment by paskino** [comment]
Yes.

you can specify the version on [this](https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/master/Wrappers/Python/conda-recipe/meta.yaml#L15) line as
```
pillow <5.4.1
```
notice no space between `<` and `5.4.1`

**Comment by dkazanc** [comment]
Thanks, apparently you have to be quite specific with version, so it should be `pillow=4.1.1`. Then I was able to build it on Windows. For students of ITT9 can we temporarily put the compiled binary on conda channel please? Should I organise a PR with this fix?

**Comment by dkazanc** [comment]
fixed with #93 by specifying pillow version

**Comment by dkazanc** [comment]
pillow=4.1.1. didn't work for Linux so I had to remove it. Is it possible to add a condition based on OS in `meta.yaml` ?

**Comment by paskino** [comment]
yes. with something like
https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/master/Wrappers/Python/conda-recipe/meta.yaml#L23
https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/master/Wrappers/Python/conda-recipe/conda_build_config.yaml#L2
```
pillow ==4.1.1 # [win]
```

**Comment by dkazanc** [comment]
@paskino thanks, will correct that. cheers
