### ISSUE TITLE
Active contours segmentation

### ISSUE THREAD

**Issue by dkazanc** [vais-ral/CCPi-Regularisation-Toolkit#97]
- To implement 2D/3D variational active contours segmentation, e.g. [Chan-Vese](https://www.ipol.im/pub/art/2012/g-cv/article.pdf)

Probably easier to add to this Toolkit rather than create Segmentation toolkit? Still the methods are variational so somewhat related.

**Comment by paskino** [comment]
There is a segmentation repo already though it's not open source yet. Let's discuss
